# This is a workflow to build the repo on ubuntu
name: build_ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.SECRET_UPDATE_SUBMODULES }} # stored in GitHub secrets 
          submodules: true
      - name: test build of Marmot
        run: | 
             git clone https://gitlab.com/libeigen/eigen.git
             cd eigen
             mkdir build
             cd build
             cmake ..
             sudo make install
             pwd
             cd ../..
             git clone https://github.com/autodiff/autodiff.git
             cd autodiff
             mkdir build
             cd build
             cmake -DAUTODIFF_BUILD_TESTS=OFF -DAUTODIFF_BUILD_PYTHON=OFF -DAUTODIFF_BUILD_EXAMPLES=OFF -DAUTODIFF_BUILD_DOCS=OFF ..
             sudo make install
             pwd
             cd ../..
             git clone --recurse-submodules https://github.com/${{ github.repository }}
             cd Marmot
             git fetch origin ${{ github.ref }}                     
             git checkout FETCH_HEAD                               
             mkdir build                                            
             cd build                                               
             cmake ..                                              
             make -j
             sudo make install
