name: Doxygen



on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content and build md-files
      uses: actions/checkout@v2 # checkout the repository content to github runner.
      with: 
          token: ${{ secrets.SECRET_UPDATE_SUBMODULES }} # stored in GitHub secrets :  
          submodules: true
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    - name: execute py script # run the run.py to get the latest data
      run: |
           python doc/buildDocumentation.py --skipDoxygen
           git config --global user.email "marmot@gmail.com"
           git config --global user.name "Marmot"
           git add -u
           git diff-index --quiet HEAD || git commit -m "update md-files"
           git status
           git push
    - uses: actions/checkout@v2
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "./doc/dconfig"
        working-directory: "."
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        
